name = "quizard-server"
main = "src/worker.js"
compatibility_date = "2026-07-01"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "QuizardLobby"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["QuizardLobby"]
